In [15]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import SimpleRNN

In [16]:
train_X = [[[0.1, 4.2, 1.5, 1.1, 2.8], [1.0, 3.1, 2.5, 0.7, 1.1], [0.3, 2.1, 1.5, 2.1, 0.1], [2.2, 1.4, 0.5, 0.9, 1.1]]]
train_X = np.array(train_X, dtype=np.float32)
print(train_X.shape)

(1, 4, 5)


In [17]:
rnn = SimpleRNN(3)

hidden_state = rnn(train_X)
print('hidden state : {}, shape: {}'.format(hidden_state, hidden_state.shape))

hidden state : [[ 0.25919518  0.08089339 -0.05048331]], shape: (1, 3)


In [18]:
rnn = SimpleRNN(3, return_sequences=True)
hidden_states = rnn(train_X)

print('hidden states : {}, shape: {}'.format(hidden_states, hidden_states.shape))

hidden states : [[[ 0.99594396  0.995177    0.9997523 ]
  [ 0.9998769   0.9664992   0.9840426 ]
  [ 0.9992054   0.98018223 -0.30249882]
  [ 0.97911763  0.9830205  -0.63342446]]], shape: (1, 4, 3)


In [19]:
# return_state : 마지막 hidden state
# return_sequences : 모든 hidden state
rnn = SimpleRNN(3, return_sequences=True, return_state=True)
hidden_states, last_state = rnn(train_X)

print('hidden states : {}, shape: {}'.format(hidden_states, hidden_states.shape))
print('last hidden state : {}, shape: {}'.format(last_state, last_state.shape))

hidden states : [[[ 0.36926952 -0.2318319  -0.5561888 ]
  [ 0.87833863  0.09057745  0.5697336 ]
  [ 0.9840636  -0.7351766  -0.96073014]
  [ 0.03895319 -0.85895073  0.89597225]]], shape: (1, 4, 3)
last hidden state : [[ 0.03895319 -0.85895073  0.89597225]], shape: (1, 3)
